[{
  "Vehicles": {
    "Vehicle Parts & Accessories": ["part_name", "compatible_makes", "condition", "price", "location", "brand", "model_year", "used_or_new"],
    "Cars": ["make", "model", "year", "price", "mileage", "fuel_type", "transmission", "color", "condition", "location", "engine_capacity_cc", "body_type", "number_of_seats", "drive_type"],
    "Motorcycles & Scooters": ["make", "model", "year", "price", "engine_capacity_cc", "fuel_type", "transmission", "color", "condition", "location"],
    "Buses & Microbuses": ["make", "model", "year", "price", "mileage", "engine_capacity_cc", "fuel_type", "capacity_passengers", "transmission", "condition", "location"],
    "Trucks & Trailers": ["make", "model", "year", "price", "mileage", "engine_capacity_cc", "fuel_type", "load_capacity_tons", "transmission", "condition", "location"],
    "Construction & Heavy Machinery": ["make", "model", "year", "price", "machine_type", "engine_capacity_cc", "condition", "location"],
    "Watercraft & Boats": ["make", "model", "year", "price", "length_ft", "engine_type", "condition", "location"],
    "Car Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Property": {
    "New Builds": ["location", "price", "bedrooms", "bathrooms", "square_feet", "property_type", "year_built", "amenities"],
    "Houses & Apartments For Rent": ["location", "price", "bedrooms", "bathrooms", "square_feet", "property_type", "lease_term", "furnished"],
    "Houses & Apartments For Sale": ["location", "price", "bedrooms", "bathrooms", "square_feet", "property_type", "year_built", "amenities"],
    "Short Let": ["location", "price", "duration", "bedrooms", "bathrooms", "furnished", "property_type"],
    "Land & Plots for Rent": ["location", "price", "area_sq_meters", "zoning_type", "lease_term"],
    "Land & Plots For Sale": ["location", "price", "area_sq_meters", "zoning_type"],
    "Event Centres, Venues & Workstations": ["location", "price", "capacity", "amenities", "availability"],
    "Commercial Property for Rent": ["location", "price", "square_feet", "property_type", "lease_term"],
    "Commercial Property for Sale": ["location", "price", "square_feet", "property_type", "year_built"]
  },

  "Mobile Phones & Tablets": {
    "Mobile Phones & Tablets": ["brand", "model", "price", "storage_gb", "ram_gb", "condition", "color", "battery_mah", "sim_type", "screen_size_inches", "os", "network_technology", "location"]
  },

  "Electronics": {
    "Laptops & Computers": ["brand", "model", "price", "processor", "ram_gb", "storage_gb", "screen_size_inches", "condition", "os", "location"],
    "TV & DVD Equipment": ["brand", "model", "price", "screen_size_inches", "type", "condition", "location"],
    "Video Game Consoles": ["brand", "model", "price", "condition", "location"],
    "Audio & Music Equipment": ["brand", "model", "price", "type", "condition", "location"],
    "Headphones": ["brand", "model", "price", "type", "condition", "location"],
    "Photo & Video Cameras": ["brand", "model", "price", "type", "resolution_mp", "condition", "location"],
    "Security & Surveillance": ["brand", "model", "price", "type", "condition", "location"],
    "Networking Products": ["brand", "model", "price", "type", "condition", "location"],
    "Printers & Scanners": ["brand", "model", "price", "type", "condition", "location"],
    "Computer Monitors": ["brand", "model", "price", "screen_size_inches", "condition", "location"],
    "Computer Hardware": ["brand", "model", "price", "type", "condition", "location"],
    "Computer Accessories": ["brand", "model", "price", "type", "condition", "location"],
    "Accessories & Supplies for Electronics": ["type", "price", "condition", "location"],
    "Video Games": ["title", "console_type", "price", "condition", "location"],
    "Software": ["title", "platform", "price", "license_type", "location"]
  },

  "Home, Furniture & Appliances": {
    "Furniture": ["type", "price", "material", "condition", "location"],
    "Lighting": ["type", "price", "condition", "location"],
    "Storage & Organization": ["type", "price", "condition", "location"],
    "Home Accessories": ["type", "price", "condition", "location"],
    "Home Appliances": ["type", "price", "brand", "condition", "location"],
    "Kitchen Appliances": ["type", "price", "brand", "condition", "location"],
    "Kitchenware & Cookware": ["type", "price", "material", "condition", "location"],
    "Household Chemicals": ["type", "price", "brand", "condition", "location"],
    "Garden Supplies": ["type", "price", "condition", "location"]
  },

  "Fashion": {
    "Women's Fashion": ["category", "brand", "price", "size", "color", "condition", "location"],
    "Men's Fashion": ["category", "brand", "price", "size", "color", "condition", "location"],
    "Baby&Kids’ Fashion": ["category", "brand", "price", "size", "color", "condition", "location"]
  },

  "Beauty & Personal Care": {
    "Hair Beauty": ["type", "brand", "price", "condition", "location"],
    "Face Care": ["type", "brand", "price", "condition", "location"],
    "Oral Care": ["type", "brand", "price", "condition", "location"],
    "Body Care": ["type", "brand", "price", "condition", "location"],
    "Fragrance": ["brand", "price", "condition", "location"],
    "Makeup": ["brand", "price", "condition", "location"],
    "Sexual Wellness": ["type", "brand", "price", "condition", "location"],
    "Tools & Accessories": ["type", "brand", "price", "condition", "location"],
    "Vitamins & Supplements": ["type", "brand", "price", "condition", "location"],
    "Massagers": ["type", "brand", "price", "condition", "location"],
    "Health & Beauty Services": ["service_type", "price_range", "location", "service_description"]
  },

  "Services": {
    "Building & Trades Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Car Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Computer & IT Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Repair Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Cleaning Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Printing Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Manufacturing Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Logistics Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Legal Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Tax & Financial Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Recruitment Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Rental Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Chauffeur & Airport Transfer Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Travel Agents & Tours": ["service_type", "price_range", "location", "service_description", "availability"],
    "Classes & Courses": ["course_name", "price_range", "location", "course_description", "availability"],
    "Child Care & Education Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Health & Beauty Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Fitness & Personal Training Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Party, Catering & Event Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "DJ & Entertainment Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Wedding Venues & Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Photography & Video Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Landscaping & Gardening Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Pet Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Other Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Repair & Construction": {
    "Electrical Equipment": ["type", "brand", "price", "condition", "location"],
    "Building Materials & Supplies": ["type", "brand", "price", "condition", "location"],
    "Plumbing & Water Systems": ["type", "brand", "price", "condition", "location"],
    "Electrical Hand Tools": ["type", "brand", "price", "condition", "location"],
    "Hand Tools": ["type", "brand", "price", "condition", "location"],
    "Measuring & Testing Tools": ["type", "brand", "price", "condition", "location"],
    "Hardware & Fasteners": ["type", "brand", "price", "condition", "location"],
    "Doors & Security": ["type", "brand", "price", "condition", "location"],
    "Windows & Glass": ["type", "brand", "price", "condition", "location"],
    "Solar Energy": ["type", "brand", "price", "condition", "location"],
    "Other Repair & Construction Items": ["type", "brand", "price", "condition", "location"],
    "Building & Trades Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Repair Services": ["service_type", "price_range", "location", "service_description", "availability"],
    "Commercial Equipment & Tools": ["type", "brand", "price", "condition", "location"],
    "Medical Equipment & Supplies": ["type", "brand", "price", "condition", "location"],
    "Safety Equipment & Protective Gear": ["type", "brand", "price", "condition", "location"],
    "Manufacturing Equipment": ["type", "brand", "price", "condition", "location"],
    "Manufacturing Materials & Supplies": ["type", "brand", "price", "condition", "location"],
    "Retail & Store Equipment": ["type", "brand", "price", "condition", "location"],
    "Restaurant & Catering Equipment": ["type", "brand", "price", "condition", "location"],
    "Stationery & Office Equipment": ["type", "brand", "price", "condition", "location"],
    "Salon & Beauty Equipment": ["type", "brand", "price", "condition", "location"],
    "Printing & Graphics Equipment": ["type", "brand", "price", "condition", "location"],
    "Stage & Event Equipment": ["type", "brand", "price", "condition", "location"],
    "Manufacturing Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Leisure & Activities": {
    "Sports Equipment": ["type", "brand", "price", "condition", "location"],
    "Massagers": ["type", "brand", "price", "condition", "location"],
    "Musical Instruments & Gear": ["type", "brand", "price", "condition", "location"],
    "Books & Table Games": ["title", "price", "condition", "location"],
    "Arts, Crafts & Awards": ["type", "price", "condition", "location"],
    "Outdoor Gear": ["type", "brand", "price", "condition", "location"],
    "Smoking Accessories": ["type", "price", "condition", "location"],
    "Music & Video": ["title", "price", "condition", "location"],
    "Fitness & Personal Training Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Babies & Kids": {
    "Toys, Games & Bikes": ["type", "price", "age_range", "condition", "location"],
    "Children's Furniture": ["type", "price", "material", "condition", "location"],
    "Children's Clothing": ["brand", "price", "size", "color", "condition", "location"],
    "Children's Shoes": ["brand", "price", "size", "condition", "location"],
    "Babies & Kids Accessories": ["type", "price", "condition", "location"],
    "Baby Gear & Equipment": ["type", "price", "condition", "location"],
    "Care & Feeding": ["type", "price", "condition", "location"],
    "Maternity & Pregnancy": ["type", "price", "condition", "location"],
    "Transport & Safety": ["type", "price", "condition", "location"],
    "Playground Equipment": ["type", "price", "condition", "location"],
    "Child Care & Education Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Food, Agriculture & Farming": {
    "Food & Beverages": ["type", "brand", "price", "condition", "location"],
    "Farm Animals": ["species", "breed", "age", "price", "condition", "location"],
    "Feeds, Supplements & Seeds": ["type", "brand", "price", "condition", "location"],
    "Farm Machinery & Equipment": ["type", "brand", "price", "condition", "location"],
    "Farm Animal Feed & Supplements": ["type", "brand", "price", "condition", "location"]
  },

  "Animals & Pets": {
    "Pet's Accessories": ["type", "brand", "price", "condition", "location"],
    "Cats & Kittens": ["breed", "age", "price", "condition", "location"],
    "Dogs & Puppies": ["breed", "age", "price", "condition", "location"],
    "Fish": ["type", "price", "condition", "location"],
    "Birds": ["species", "price", "condition", "location"],
    "Other Animals": ["type", "price", "condition", "location"],
    "Pet Services": ["service_type", "price_range", "location", "service_description", "availability"]
  },

  "Jobs": {
    "Advertising & Marketing Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Accounting & Finance Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Arts & Entertainment Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Childcare & Babysitting Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Clerical & Administrative Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Computing & IT Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Construction & Skilled Trade Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Consulting & Strategy Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Customer Services Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Driver Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Engineering & Architecture Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Farming & Veterinary Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Gardening & Landscaping Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Health & Beauty Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Healthcare & Nursing Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Hotel Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Housekeeping & Cleaning Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Human Resources Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Internship Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Legal Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Logistics & Transportation Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Management Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Manual Labour Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Manufacturing Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Mining Industry Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Office Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Part-Time & Weekend Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Quality Control & Assurance Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Research & Survey Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Restaurant & Bar Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Retail Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Sales & Telemarketing Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Security Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Sports Club Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Teaching Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Technology Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Travel & Tourism Jobs": ["job_title", "company", "salary_range", "location", "employment_type"],
    "Other Jobs": ["job_title", "company", "salary_range", "location", "employment_type"]
  },

  "Seeking Work / CVs": {
    "Accounting & Finance CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Advertising & Marketing CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Arts & Entertainment CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Childcare & Babysitting CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Clerical & Administrative CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Computing & IT CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Construction & Skilled Trade CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Consulting & Strategy CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Customer Services CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Driver CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Engineering & Architecture CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Farming & Veterinary CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Gardening & Landscaping CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Health & Beauty CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Healthcare & Nursing CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Hotel CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Housekeeping & Cleaning CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Human Resources CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Internship CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Legal CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Logistics & Transportation CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Management CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Manual Labour CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Manufacturing CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Mining Industry CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Office CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Part-Time & Weekend CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Quality Control & Assurance CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Research & Survey CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Restaurant & Bar CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Retail CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Sales & Telemarketing CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Security CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Sports Club CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Teaching CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Technology CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Travel & Tourism CVs": ["name", "experience_years", "skills", "location", "desired_salary"],
    "Other CVs": ["name", "experience_years", "skills", "location", "desired_salary"]
  }
}
]